version: "3"
services:
  backend:
    container_name: ckd-backend
    build: ./backend
    volumes:
      - ./backend:/app/
    ports:
      - 5000:5000
  frontend:
    build: ./frontend
    command: yarn start
    container_name: ckd-frontend
    volumes:
      - ./frontend:/app/
      - /app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - backend